name: Pre-Commit

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

env:
  TERRAFORM_DOCS_VERSION: v0.16.0

jobs:
  collectInputs:
    name: Collect workflow inputs
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.dirs.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Get root directories
        id: dirs
        uses: clowdhaus/terraform-composite-actions/directories@eb963bdb7f8b1c64e29b6f4b08c7e5eab1be4bd2 # v1.3.0

  preCommitMinVersions:
    name: Min TF pre-commit
    needs: collectInputs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.collectInputs.outputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@7009a64f997e57294f56f7c13b584e61574e7be9 # v1.0.3
        with:
          directory: ${{ matrix.directory }}

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory !=  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@eb963bdb7f8b1c64e29b6f4b08c7e5eab1be4bd2 # v1.3.0
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          args: 'terraform_validate --color=always --show-diff-on-failure --files ${{ matrix.directory }}/*'

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory ==  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@eb963bdb7f8b1c64e29b6f4b08c7e5eab1be4bd2 # v1.3.0
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          args: 'terraform_validate --color=always --show-diff-on-failure --files $(ls *.tf)'

  preCommitMaxVersion:
    name: Max TF pre-commit
    runs-on: ubuntu-latest
    needs: collectInputs
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@7009a64f997e57294f56f7c13b584e61574e7be9 # v1.0.3

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@eb963bdb7f8b1c64e29b6f4b08c7e5eab1be4bd2 # v1.3.0
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          terraform-docs-version: ${{ env.TERRAFORM_DOCS_VERSION }}
